### ISSUE TITLE
Add it to Elm package repository

### ISSUE THREAD

**Issue by rhaps0dy** [bmatcuk/elm-webaudio#2]
Come on, it'll be so convenient to include!

**Comment by bmatcuk** [comment]
My intention was to add it to the package repo eventually, lol... I've started the process =) Because the project uses native code, apparently there must be a review process before the project will be accepted in their package repo. I'll update this issue as progress is made.

Thanks!

**Comment by rhaps0dy** [comment]
Don't mention it.
Nice library btw. I've been using it today and it worked perfectly.

**Comment by bmatcuk** [comment]
Cool! =) Thanks!

**Comment by kmarekspartz** [comment]
This would be great! @bicyclesforthemind and I are trying it out.

**Comment by bmatcuk** [comment]
Just waiting on someone to do the code review and accept the project... you can view the progress of that here: https://github.com/elm-lang/package.elm-lang.org/issues/36

**Comment by joaomilho** [comment]
+1

**Comment by bmatcuk** [comment]
Thanks =)

**Comment by bmatcuk** [comment]
Closing this since I've abandoned the project. See [trotha01's implementation](https://github.com/trotha01/elm-webaudio).
